version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
  pre_build:
    commands:
      - npm pkg delete scripts.prepare
      - npm ci
  
  build:
    commands:
      - npm run build