name: "Live 05 CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: "18.x"
        cache: "npm"
    
    - run: npm pkg delete scrips.prepare

    - name: Install dependencies
      run: npm ci

    - name: Linting
      run: npm run ci:lint

    - name: Typechecking
      run: npm run typecheck

    - name: Test
      run: npm run test
